# Generated by Django 4.1.7 on 2023-03-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='tape',
            name='movies',
            field=models.ManyToManyField(to='main_app.movie'),
        ),
    ]
