# Generated by Django 4.1.7 on 2023-03-07 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_tape_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='director',
            new_name='imdb_id',
        ),
    ]
